import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PageHead, Panel, Shell, Tag } from "@/components/bms/shell";
import { dailyBrief, REPORT_DATE, shiftReport } from "@/lib/demo-data";

export const Route = createFileRoute("/report")({
  head: () => ({
    meta: [
      { title: "Generate Shift Report | Engineering Intelligence Layer" },
      {
        name: "description",
        content:
          "Auto-generated hotel engineering shift report: energy and water variance, critical alerts, maintenance recommendations and avoidable cost.",
      },
      { property: "og:title", content: "Generate Shift Report" },
      {
        property: "og:description",
        content: "Yesterday's engineering summary and executive brief, generated by AI.",
      },
    ],
  }),
  component: ReportPage,
});

function ReportPage() {
  const [sent, setSent] = useState(false);
  const [exported, setExported] = useState(false);

  return (
    <Shell>
      <PageHead
        title="Generate Shift Report"
        subtitle={`Auto-generated engineering summary for the operating day ending ${REPORT_DATE}`}
        right={
          <div className="flex gap-2">
            <button
              onClick={() => setExported(true)}
              className="rounded border border-border px-3 py-1.5 text-sm font-medium hover:bg-muted"
            >
              {exported ? "PDF ready" : "Export PDF"}
            </button>
            <button
              onClick={() => setSent(true)}
              className="rounded bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            >
              {sent ? "Sent to Engineering Team" : "Send to Engineering Team"}
            </button>
          </div>
        }
      />

      <div className="grid gap-4 xl:grid-cols-[1fr_360px]">
        <div className="space-y-4">
          <Panel title="Yesterday's Engineering Summary">
            <dl className="grid gap-3 sm:grid-cols-3">
              <Metric label="Energy" value={shiftReport.energy} sub={`Expected ${shiftReport.energyExpected}`} tone="warn" />
              <Metric label="Variance" value={shiftReport.variance} sub="vs AI baseline" tone="warn" />
              <Metric label="Water" value={shiftReport.water} sub={`Expected ${shiftReport.waterExpected}`} tone="warn" />
              <Metric label="Critical equipment alerts" value={String(shiftReport.criticalAlerts)} sub="AHU-04, Chiller-02" tone="crit" />
              <Metric label="Maintenance recommendations" value={String(shiftReport.recommendations)} sub="3 high, 2 medium" />
              <Metric label="Estimated avoidable cost" value={shiftReport.avoidableCost} sub="per day at current tariff" tone="crit" />
            </dl>
          </Panel>

          <Panel title="Executive Summary" hint="AI-generated narrative for engineering leadership">
            <p className="text-sm leading-relaxed">{shiftReport.summary}</p>
          </Panel>

          <Panel title="Open engineering actions">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left">
                  {["Asset", "Observation", "Action", "Impact", "Priority"].map((h) => (
                    <th key={h} className="label-xs py-2 pr-3 font-medium">
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {dailyBrief.map((b) => (
                  <tr key={b.asset} className="border-b border-border/70">
                    <td className="num py-2.5 pr-3 font-medium">{b.asset}</td>
                    <td className="py-2.5 pr-3">{b.metric}</td>
                    <td className="py-2.5 pr-3">{b.action}</td>
                    <td className="num py-2.5 pr-3 text-crit">₹{b.impactPerDay.toLocaleString()}/day</td>
                    <td className="py-2.5 pr-3">
                      <Tag tone={b.priority === "HIGH" ? "crit" : "warn"}>{b.priority}</Tag>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Panel>
        </div>

        <div className="space-y-4">
          <Panel title="Report configuration">
            <ul className="space-y-2 text-sm">
              {[
                "Shift: Night (22:00 – 06:00)",
                "Recipients: Chief Engineer, Engineering Manager",
                "Sections: Energy, Water, Equipment, Actions",
                "Distribution: Email + hotel intranet",
              ].map((l) => (
                <li key={l} className="flex items-center gap-2 text-muted-foreground">
                  <span className="h-1.5 w-1.5 rounded-full bg-ok" />
                  {l}
                </li>
              ))}
            </ul>
          </Panel>
          <Panel title="Delivery status">
            <p className="text-sm">
              {sent ? (
                <span className="text-ok">Report dispatched to the engineering distribution list.</span>
              ) : (
                <span className="text-muted-foreground">Report ready. Not yet dispatched.</span>
              )}
            </p>
            <p className="mt-2 text-sm">
              {exported ? (
                <span className="text-ok">PDF export generated (demo).</span>
              ) : (
                <span className="text-muted-foreground">No export generated yet.</span>
              )}
            </p>
          </Panel>
        </div>
      </div>
    </Shell>
  );
}

function Metric({
  label,
  value,
  sub,
  tone,
}: {
  label: string;
  value: string;
  sub: string;
  tone?: "warn" | "crit";
}) {
  return (
    <div className="rounded border border-border bg-muted/30 p-3">
      <dt className="label-xs">{label}</dt>
      <dd className={`num mt-1 text-xl font-semibold ${tone === "crit" ? "text-crit" : tone === "warn" ? "text-warn" : ""}`}>
        {value}
      </dd>
      <dd className="mt-1 text-xs text-muted-foreground">{sub}</dd>
    </div>
  );
}